### ISSUE TITLE
Clase DatosRgb

### ISSUE THREAD

**Issue by EstebanAGG** [AbelGarcia09/PaletaColores#11]
¿Por qué habéis creado una clase DatosRgb?
Si no es necesaria, debéis eliminarla.

**Comment by NarcisoDAM** [comment]
La clase DatosRgb.java ha sido eliminada ya. Efectivamente no tenia ninguna utilidad. He pasado los métodos que había implementados en esa clase a la otra (Rgb.java) y hemos conseguido el mismo resultado con una clase menos.
