### ISSUE TITLE
Fallo botón añadir

### ISSUE THREAD

**Issue by EstebanAGG** [AbelGarcia09/PaletaColores#3]
Al añadir un color, se desactiva el botón añadir y no me deja añadir más colores a la lista.
![imagen](https://user-images.githubusercontent.com/93192427/149983733-404e52bf-a8e0-4991-a10e-047163dc78d5.png)

**Comment by AbelGarcia09** [comment]
Estaba hecho así a propósito. De todas formas ya está solucionado.

**Comment by EstebanAGG** [comment]
Pues no entiendo qué ventaja puede tener que esto funcione así.
Todavía no puedo ver eso solucionado. ¿Lo has subido al repositorio remoto?

**Comment by AbelGarcia09** [comment]
Sí. He eliminado el código en el que dejaba que el elemento de la lista quedase seleccionado al añadir un elemento.
No tenía ninguna ventaja la verdad.
