### ISSUE TITLE
Definición de propiedades en la clase Rgb

### ISSUE THREAD

**Issue by EstebanAGG** [AbelGarcia09/PaletaColores#4]
Cuándo se definen propiedades, no se hace del modo simple, si no del base.

 Me explico:
  
`   private **IntegerProperty** valorEntero = new SimpleIntegerProperty("valorEntero",0); `

**Comment by AbelGarcia09** [comment]
Vale. Lo he cambiado.

**Comment by EstebanAGG** [comment]
Lo mismo que en la anterior Issue #5 . Debéis hacer una rama nueva para cambiar el código. No se debe hacer push sobre la rama master.
