### ISSUE TITLE
Getters, Setters y propiedades.

### ISSUE THREAD

**Issue by EstebanAGG** [AbelGarcia09/PaletaColores#5]
En la clase Rgb:

   Los getters, no devuelven propiedades, si no valores. 
 **Es el método, redProperty() el que debe devolver la propiedad.** --> Revisad la teoría al respecto.

  ¿Por qué no están definidos los setters?. si se necesita modificar el valor de un objeto RGB no se puede hacer.

**Comment by AbelGarcia09** [comment]
He creado nuevos getters que devuelvan valores y a parte he dejado los que devuelven la propiedad. Así que si lo he entendido bien, debería de estar solucionado.
Respecto a los setters, no están creados porque en este programa no había ninguna intención de usarlos.

**Comment by EstebanAGG** [comment]
La clase Rgb es correcta. Falta que me expliques en otra issue, para qué el extractor.

Para solucionar cualquier problema o implementar cualquier funcionalidad nueva, **debéis hacer una rama.** Y cuando hagáis el merge con el master, enlazarlo para que se cierre la issue. Escribiendo una almohadilla # en el comentario del merge os dejará seleccionar la issue y la cerrará. Igualmente la enlazará y se podrá ver qué merge ha solucionadol la issue.
