### ISSUE TITLE
Extractor en la clase Rgb

### ISSUE THREAD

**Issue by EstebanAGG** [AbelGarcia09/PaletaColores#6]
¿Por qué habéis creado un extractor en la clase Rgb?

**Comment by AbelGarcia09** [comment]
Para pasar las propiedades al observableList y para dejar la posibilidad de poder ordenar la lista de algún modo en un futuro, o modificar algún elemento.
En cualquier caso, creo que no entiendo realmente bien como funciona.

**Comment by EstebanAGG** [comment]
Si no implementáis los setter porque no se van a utilizar, ¿immplementáis el extractor por si en el futuro se va a ordenar la lista?, ¿con qué criterio la ordenaríais?*

**Comment by AbelGarcia09** [comment]
La ordenaríamos de colores más claros a más oscuros o al revés
