### ISSUE TITLE
No permitir guardar colores duplicados

### ISSUE THREAD

**Issue by EstebanAGG** [AbelGarcia09/PaletaColores#8]
Otra mejora consiste en no permitir guardar valores duplicados en la lista.

**Comment by NarcisoDAM** [comment]
Hemos intentado solucionar el problema de que se guarden registros duplicados. En teoría nos parecía algo sencillo, y añadiendo una simple condición a la hora de guardar un elemento en la lista debería funcionar. 
Nuestra lógica ha sido esta:

`if(listaRgb.contains(rgb)){     
            System.out.println("El color ya esta guardado.");
        }else{
            listaRgb.add(rgb);
        }`

Y lo hemos añadido pero el resultado ha sido que no cambia nada, parece que ignora la condición y sigue añadiendo registros aunque el contenido sea el mismo. No se si la lógica esta bien o no, pero vamos a probar esta tarde tomando directamente los valores que podemos extraer del objeto rgb y comparandolos con los valores extraidos de los elementos de la lista, aunque ya tendremos que añadir un bucle y hacerlo de manera diferente.

**Comment by AbelGarcia09** [comment]
Al final si hemos conseguido que no haya elementos duplicados.

**Comment by EstebanAGG** [comment]
Lo habéis conseguido, pero en términos de usabilidad no es correcto del todo.
El usuario pincha en el botón y no sabe qué ocurre en vuestra aplicación, si se añade algo, si no se añade, el motivo de que no se añada, ...
